version: '3.8'
services:
  web: 
    hostname: web
    container_name: web
    restart: always
    image: marcinkujawski/docker-flask:2.0
    ports:
      - "80:5000"
    networks: 
      - appnet
    links: 
      - "database:web"

  database:
    hostname: pg_db
    container_name: pg_db
    restart: always
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=securePass123!"
      - "POSTGRES_USER=app_user"
      - "POSTGRES_DB=app_db"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - appnet

volumes:
  pg_data:
    name: postgres_data

networks:
  appnet:
    name: flask_network
